name: Publish signed image to GitHub Container Registry
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # required for signing the image with GitHub OIDC token
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/janeczku/cosign-example:commit-${{ github.sha }},ghcr.io/janeczku/cosign-example:latest
      - name: Sign image with Github OIDC token
        run: |
          cosign sign --yes ghcr.io/janeczku/cosign-example:latest
